### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by ghost** [marckoch/UnitConverter#1]
Exception in test #8

java.lang.NumberFormatException: For input string: "random"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:651)
	at stage5.MainKt.processInput(Main.kt:103)
	at stage5.MainKt.main(Main.kt:38)
	at stage5.MainKt.main(Main.kt)

Please find below the output of your program during this failed test.
Note that the '>' character indicates the beginning of the input line.

---

Enter what you want to convert (or exit): > Random string without numbers

**Comment by marckoch** [comment]
They have changed the project after I had completed it. I see my code as completed with green check on 09.02.2021. weird...
